### ISSUE TITLE
Run Github Action tests without database rollback

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert-storage#63]
```
E       sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_observation_name"
E       DETAIL:  Key (name)=(OBS1) already exists.
E
E       [SQL: INSERT INTO observation (name, x_axis, values, errors, experiment_id) VALUES (%(name)s, %(x_axis)s::VARCHAR[], %(values)s::FLOAT[], %(errors)s::FLOAT[], %(experiment_id)s) RETURNING observation.id]
E       [parameters: {'name': 'OBS1', 'x_axis': ['0', '1', '2'], 'values': [1.0, 2.0, 3.0], 'errors': [0.1, 0.2, 0.3], 'experiment_id': 29}]
E       (Background on this error at: http://sqlalche.me/e/14/gkpj)
```

**Comment by markusdregi** [comment]
I don't understand the motivation for this issue. Care to elaborate?

**Comment by dotfloat** [comment]
Each test rollbacks the changes they do. This is good for local development and to make sure that tests don't rely on each other, but it does mean that if there are incorrect SQL constraints (which inspired this issue in the first place) then it doesn't show up easily. We shouldn't do rollbacks on Github Actions.

The incorrect SQL constraint has been fixed, but the issue was that we had a uniqueness constraint on just the `name` column, rather than `name` and `experiment_id`. This was merged into `main` but could've been picked up by GA.

**Comment by markusdregi** [comment]
So what is the suggestion? To not roll-back between tests and let the different tests all use the same database?

**Comment by dotfloat** [comment]
Yes. For GA by default only. We could add a `ERT_STORAGE_TEST_NO_ROLLBACK` environment variable.

**Comment by markusdregi** [comment]
I still don't see the argument for not running the tests in isolation during CI. Because the rules for reverting the state could be wrong? Should they not all start with a blank state?

**Comment by dotfloat** [comment]
Each test is currently ran on a blank database, but our users will most likely have data in the databases. The tests should both be able to run in isolation and with some previous state. The latter is not being tested at the moment.

**Comment by jondequinor** [comment]
Could that mean that GA tests failures could potentially hard to debug locally? Isn't that a hard no?

Also, db design is hard, we should design it deliberately, continuously—not by chance.

**Comment by jondequinor** [comment]
Say test 3 fails on GA. I run it locally. It passes. Okay, I know there's no rollback on GA so I disable it. It still passes. 

What do I do now? I need to either run test 0-3 or traverse back from 3?

Or maybe I misunderstood.

**Comment by markusdregi** [comment]
I agree with Jonas. It sounds to me like what you want is functional / integration testing of the database representing its expected usage over time. I think that is best left for dedicated tests, not by running the unit tests towards the same database.

I suggest we close this issue...

**Comment by dotfloat** [comment]
> Does that mean that GA tests failures could potentially be hard to debug locally? Isn't that a hard no?

The alternative is that there is no error in GA and it hits the users. This is even harder to debug.

> I agree with Jonas. It sounds to me like what you want is functional / integration testing of the database representing its expected usage over time. I think that is best left for dedicated tests, not by running the unit tests towards the same database.

Yes this is what I want. But because that is a time-consuming solution, I proposed this solution as a simple-to-implement change that might catch a few more errors.

Everyone in this discussion has already spent more time thinking about this issue than it would take to actually implement.

> I suggest we close this issue...

... due to a PR solving this being merged.

**Comment by markusdregi** [comment]
> ... I proposed this solution as a simple-to-implement change that might catch a few more errors.

That again will leave other errors undetected and potentially give false failures. Running the tests without rollback is not a way to have better testing, just different testing.

**Comment by dotfloat** [comment]
> That again will leave other errors undetected and potentially give false failures. Running the tests without rollback is not a way to have better testing, just different testing. And in this case I don't see that it is a good tradeoff!

In the PR that resolves this issue, I add a new GA job. It's not a replacement. Besides, having a way to disable rollback is very useful for test debugging and populating the database with rudimentary data.

**Comment by markusdregi** [comment]
Aight, that resolves the issue of reducing the testing at least 👍🏻 But, are we not worried this will give false failures? Or do we expect all unit tests to be written such that they can be ran in conjunction towards a single database? That sounds like a pretty non-standard unit test requirement 🤔

**Comment by dotfloat** [comment]
Tests can and should run in non-pristine conditions.

**Comment by markusdregi** [comment]
I'm don't think the community at large agrees on that for unit tests. I would argue that unit tests should preferably be easy to reason about, possible to read in isolation and aggressive on failing if things behave oddly.

Sounds to me like you want to write unit tests `testx` such that `testx` applies some unit/atomic operation and then afterwards verifies that the state before and after the operation is in accordance with how the operation is assumed to behave.  Which would imply that afterwards you could (in theory) choose to run any subset of your unit tests in any order with the state from one test being passed on to the next test. That is an interesting idea, but I would like to stress that it puts a higher responsibility on the ones writing tests and that it is probably not what most people believe a unit test is. Do you know of anyone that has done something like that successfully?

**Comment by dotfloat** [comment]
The tests running against a database are, by definition, integration tests. While it's probably a discussion of semantics, the requirements for what an integration test should be is more relaxed and is more general than what a unit test is.

However, the problem that I'm trying to work around is that currently we have a collection of tests, all of which we guarantee will run in isolation on a pristine database. We are not testing whether these tests will also work when run in sequence. I will posit that an integration test should pass in an environment that we can foresee the user having. In this case it means a non-empty database. The test should not assume pristine conditions, just like a test creating a file should not expect a pristine, newly formatted disk (see: pytest's tmpdir implementation, which doesn't delete the directories it creates).

The cost of doing testing in sequence and not independently was 15 minutes of my time. We can make it better by running tests in random order, but that would be something that I'd have to search for and implement, so I didn't bother.

**Comment by markusdregi** [comment]
I see your point. At the same time, when data storage is the responsibility, it sounds like the closest thing you'll get to a unit test is something that also hits the database. And although it might not strictly be a formal unit test anymore I still think the motivation of unit tests carries weight. That is to have tests that are easy to read and reason about, that verifies that a particular feature works as intended in isolation and for which the result is easy to reproduce.

If you at the same time want all these tests to also be possible to run in conjunction with data leakage, I think this should be written in the readme under development guidelines. And, we should verify that all current tests are written in this way and that the rest of the squad is motivated to follow this through.

When it comes to the order, there is already plenty of `pytest` features and extensions to randomise the order of the tests executed. So, no need to implement that ourselves ;)
